name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.0
publish_to: none
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    git: https://github.com/kumsumit/record_platform_interface.git
  path: ^1.8.3

dev_dependencies:
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
